"""Add CardDetail model

Revision ID: 0087d93b1567
Revises: 89672b34a43f
Create Date: 2021-01-23 17:02:20.053251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0087d93b1567'
down_revision = '89672b34a43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('easiness', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.Date(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'last_review', 'next_review', name='_card_id_last_review_next_review_uc')
    )
    op.create_index(op.f('ix_cards_details_id'), 'cards_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_details_id'), table_name='cards_details')
    op.drop_table('cards_details')
    # ### end Alembic commands ###
