"""Remove CardDetail and move attrs to Card

Revision ID: 166e08661e90
Revises: a011158c97bf
Create Date: 2021-02-04 21:38:30.997919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166e08661e90'
down_revision = 'a011158c97bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('easiness', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('interval', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('prev_easiness', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('prev_interval', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('prev_repetitions', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('prev_review_date', sa.Date(), nullable=True))
    op.add_column('cards', sa.Column('quality', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('repetitions', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('review_date', sa.Date(), nullable=True))
    op.drop_column('stacks', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'review_date')
    op.drop_column('cards', 'repetitions')
    op.drop_column('cards', 'quality')
    op.drop_column('cards', 'prev_review_date')
    op.drop_column('cards', 'prev_repetitions')
    op.drop_column('cards', 'prev_interval')
    op.drop_column('cards', 'prev_easiness')
    op.drop_column('cards', 'interval')
    op.drop_column('cards', 'easiness')
    # ### end Alembic commands ###
