"""Add description column to Queue model

Revision ID: 58060abf1f91
Revises: e90f1f25a0a9
Create Date: 2022-05-09 01:12:30.938637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58060abf1f91"
down_revision = "e90f1f25a0a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queues", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queues", "description")
    # ### end Alembic commands ###
