"""Add size column to Board model

Revision ID: 5878f42bdc30
Revises: 70eab37c5cb1
Create Date: 2020-11-15 11:13:44.925052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5878f42bdc30'
down_revision = '70eab37c5cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'size')
    # ### end Alembic commands ###
