"""Add latest column to CardDetail model

Revision ID: a011158c97bf
Revises: 0087d93b1567
Create Date: 2021-01-24 18:39:06.482375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a011158c97bf'
down_revision = '0087d93b1567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards_details', sa.Column('latest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards_details', 'latest')
    # ### end Alembic commands ###
