"""Add created_at column to Item and Queue models

Revision ID: e90f1f25a0a9
Revises: 157d346f09b5
Create Date: 2022-05-08 17:11:06.546705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e90f1f25a0a9"
down_revision = "157d346f09b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("created_at", sa.Date(), nullable=True))
    op.add_column("queues", sa.Column("created_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queues", "created_at")
    op.drop_column("items", "created_at")
    # ### end Alembic commands ###
